#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

wmakeLnInclude  library
wmakeLnInclude  solver

export WM_NCOMPPROCS=6

#use global binary paths
export OF_APPBIN_DIR=$FOAM_APPBIN
export OF_LIBBIN_DIR=$FOAM_LIBBIN

#use local library paths
# export OF_APPBIN_DIR=$FOAM_USER_APPBIN
# export OF_LIBBIN_DIR=$FOAM_USER_LIBBIN


wmake $makeType library
wmake solver/vssFoam
wmake solver/vssDyMFoam

doxygen ../.doxygen_cfg > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
