#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

wclean solver/vssFoam
wclean solver/vssDyMFoam
wclean $makeType library

find . -name "*.dep" -delete
find . -name "*.o" -delete

wmakeLnInclude  -u library
wmakeLnInclude  -u solver
# ----------------------------------------------------------------- end-of-file
